### ISSUE TITLE
I'm too dumb to understand...

### ISSUE THREAD

**Issue by Panderine** [Abbie5/emi-ores#6]
Can you explain how to read the screen? What is "bot" for example en diamond oregen?

**Comment by Abbie5** [comment]
I used "bot" as shorthand for "bottom (of the world)", ie. y=-64 in the overworld or y=0 in the nether. I understand that this is not intuitive and am working on an update to fix this issue.

**Comment by Panderine** [comment]
Ok but what does it mean "bot-80" "bot" and then "bot+80". If bot is the bottom, ie bedrock, how do you go "bot-80" ? I guess the middle number is the most abundant y-level ? so if it says "BOT" there you should mine at bedrock?? I'm reading this right?

**Comment by Abbie5** [comment]
Kind of, the distribution only describes how the game *attempts* to generate ores. It attempts to generate diamond ore the most at the bottom of the world (y=-64), but the bottom 5 y levels have varying levels of bedrock which blocks ore generation, so it's actually better to mine a little higher than that. This is assuming default generation settings of course, if you were using a mod or data pack that replaced the bedrock layer with deepslate, mining at y=-64 (or as close as you can get without falling into the void) would be best for getting diamonds. 

As for the "below bottom" and "above top" numbers, of course the game can't actually place blocks there, so they are effectively "cut off" from the distribution graph. The actual diamond distribution graph would look something like a right-angled triangle with its corner at y=-64 rather than the isosceles one used in the representative image in the mod.

Note that the "graphs" in the mod are neither accurate nor to scale, they are just a visual representation of the *type* of distribution (triangle, uniform or trapezoid) used in the given placed feature.

Sorry for the long explanation, again I am working on making the mod more intuitive so hopefully it will not be necessary in the future.

**Comment by Panderine** [comment]
It's perfectly clear now, thanks! I guess confussion comes from JER as the defacto way of showing this information, so I expected the oregen graph to be somehow the same. I added your mod to my playthrough of the Prominence II RPG modpack since it has a custom worldgen and lots of mod's added ores. It definetly needs something like your mod. We Will Watch Your Career With Great Interest !

**Comment by walksanatora** [comment]
mabey instead of "bottom" mabey remove the lower-bound and make the middle say bedrock
